"""
Quick API Key Setup Wizard
Run this to configure your API keys interactively
"""
import os
from pathlib import Path

def create_env_file():
    print("=" * 60)
    print("API KEY CONFIGURATION WIZARD")
    print("=" * 60)
    
    env_path = Path("backend/.env")
    
    print(f"\nCreating config file: {env_path}")
    
    # Check if .env already exists
    if env_path.exists():
        response = input("\n⚠ .env file already exists. Overwrite? (y/n): ")
        if response.lower() != 'y':
            print("Cancelled.")
            return
    
    print("\n" + "=" * 60)
    print("STEP 1: STRIPE (REQUIRED)")
    print("=" * 60)
    print("You said you have this!")
    stripe_key = input("Paste your Stripe secret key (starts with sk_): ").strip()
    
    print("\n" + "=" * 60)
    print("STEP 2: SENDGRID (RECOMMENDED)")
    print("=" * 60)
    print("FREE: 100 emails/day")
    print("Get it here: https://signup.sendgrid.com/")
    print("\nAfter signup:")
    print("  1. Verify your email")
    print("  2. Settings → API Keys → Create API Key")
    print("  3. Name: 'Anti-Lust Guardian'")
    print("  4. Permissions: Full Access")
    print("  5. Copy the key (starts with SG.)")
    
    sendgrid_key = input("\nPaste SendGrid API key (or press Enter to skip): ").strip()
    
    print("\n" + "=" * 60)
    print("STEP 3: JWT SECRET (REQUIRED)")
    print("=" * 60)
    print("Generating random secret key...")
    
    import secrets
    jwt_secret = secrets.token_urlsafe(32)
    print(f"Generated: {jwt_secret[:20]}...")
    
    print("\n" + "=" * 60)
    print("STEP 4: OPENAI (OPTIONAL)")
    print("=" * 60)
    print("Only needed for AI features")
    print("Get it here: https://platform.openai.com/api-keys")
    
    openai_key = input("\nPaste OpenAI API key (or press Enter to skip): ").strip()
    
    # Create .env file
    env_content = f"""# Anti-Lust Guardian API Configuration
# Generated by setup wizard

# === PAYMENT (REQUIRED) ===
STRIPE_SECRET_KEY={stripe_key}

# === EMAIL ALERTS (RECOMMENDED) ===
SENDGRID_API_KEY={sendgrid_key if sendgrid_key else 'SG.your_key_here'}

# === SECURITY (REQUIRED) ===
JWT_SECRET_KEY={jwt_secret}

# === AI FEATURES (OPTIONAL) ===
OPENAI_API_KEY={openai_key if openai_key else 'sk-your_key_here'}

# === DATABASE ===
DATABASE_URL=sqlite:///./data/app.db

# === CORS ===
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080

# === LIMITS ===
RATE_LIMIT_PER_MINUTE=100
MAX_IMAGE_SIZE_MB=10
MAX_TEXT_LENGTH=10000
"""
    
    # Write file
    env_path.write_text(env_content)
    
    print("\n" + "=" * 60)
    print("✅ CONFIGURATION COMPLETE!")
    print("=" * 60)
    print(f"\nCreated: {env_path}")
    print("\nYour configuration:")
    print(f"  ✅ Stripe: {'Configured' if stripe_key else 'Missing'}")
    print(f"  {'✅' if sendgrid_key else '⚠'} SendGrid: {'Configured' if sendgrid_key else 'Missing (emails wont work)'}")
    print(f"  ✅ JWT Secret: Generated")
    print(f"  {'✅' if openai_key else '⚠'} OpenAI: {'Configured' if openai_key else 'Not set (optional)'}")
    
    print("\n" + "=" * 60)
    print("NEXT STEPS:")
    print("=" * 60)
    print("1. Test your configuration:")
    print("   python backend/test_final_complete.py")
    print("\n2. Deploy to Google Cloud Run:")
    print("   See DEPLOYMENT_GUIDE.md")
    
    if not sendgrid_key:
        print("\n⚠ WARNING: SendGrid not configured")
        print("   Email alerts won't work until you add SENDGRID_API_KEY")
        print("   Get free key at: https://signup.sendgrid.com/")

if __name__ == "__main__":
    create_env_file()
